# Generated by Django 5.1.6 on 2025-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),  # Replace with the previous migration file name
    ]

    operations = [
        # Step 1: Remove the foreign key constraint from the User model
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        
        # Step 2: Delete the Role model
        migrations.DeleteModel(
            name='Role',
        ),
        
        # Step 3: Add a new CharField for role in the User model
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                max_length=50,
                choices=[('admin', 'Admin'), ('user', 'User')],
                default='user',
            ),
        ),
    ]