# Generated by Django 5.1.6 on 2025-03-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20250305_1204"),
    ]

    operations = []
