# Generated by Django 5.1.6 on 2025-03-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_is_staff_remove_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(default="Medium", max_length=50),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="Not Started", max_length=50),
        ),
    ]
